// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	tutorialSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
	resourcesSidebar: [{ type: 'autogenerated', dirName: 'resources' }],
};

module.exports = sidebars;
