import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
	tutorialSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
	resourcesSidebar: [{ type: 'autogenerated', dirName: 'resources' }],
};

module.exports = sidebars;
