import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
	tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorials' }],
};

module.exports = sidebars;
